### ISSUE TITLE
bona_fide is now present in a scope in GA4GH token

### ISSUE THREAD

**Issue by blankdots** [CSCfi/beacon-python#107]
#### Description
We need to modify the workflow based on which we validate a user's `bona_fide` at the `user_info` endpoint.

Currently we forward the token to the user info endpoint indifferently of the presence of the `bona_fide` scope in the JWT. We need to first check if the `bona_fide` was requested and then do the check at the `user_info` endpoint.

e.g. JWT:
```
scope": [
    "bona_fide_status",
    "ga4gh",
    "openid",
    "permissions_rems"
  ],
```

https://docs.google.com/document/d/11Wg-uL75ypU5eNu2p_xh9gspmbGtmLzmdq5VfPHBirE/edit#heading=h.recbey6qswyl

#### DoD (Definition of Done)
New workflow implemented that will adhere to the GA4GH standard specification for `bona_fide`.

Documentation Update as well.

#### Testing
Unit test, Integration testing

**Comment by teemukataja** [comment]
Note to self:
Check bona fide status in `ga4gh.py` alongside the dataset permissions (requested from /userinfo)
