### ISSUE TITLE
beacon_init can't parse all variants in a filtered vcf

### ISSUE THREAD

**Issue by jamespeapen** [CSCfi/beacon-python#180]
#### Describe the bug
`beacon_init` doesn't read all variants in a vcf that is filtered for one sample. The vcf parsing and the tables don't seem to need genotype information so I'm not sure why this isn't working. 

#### To Reproduce
Steps to reproduce the behaviour:
1. Filter for sample HG00096 with 

    `bcftools view -s HG00096 data/ALL.chrMT.phase3_callmom-v0_4.20130502.genotypes.vcf.gz > one_site.vcf`
1. `beacon_init one_site.vcf data/example_metadata.json`

```sql
SELECT COUNT(*) FROM beacon_data_table;
```
```
13
```

#### Expected behavior
All variants from file are loaded into table. 
```sql
SELECT COUNT(*) FROM beacon_data_table;
```
```
4242
```

### Additional context

The filtering doesn't seem to be removing any variants.
```bash
zcat < data/ALL.chrMT.phase3_callmom-v0_4.20130502.genotypes.vcf.gz | wc -l
# 3902

wc -l one_site.vcf
# 3906
# The extra lines are from bcftools info
```

During execution, the `beacon_init` logs seem to show that its receiving all the variants and inserting them.

**Comment by blankdots** [comment]
this seems related to  https://github.com/CSCfi/beacon-python/issues/174 and it caused by https://github.com/brentp/cyvcf2 version we were using when that loader was built, try version `0.10.1` until we have time to look into this (I don't have an ETA).
