### ISSUE TITLE
Index prevents insertion of rows

### ISSUE THREAD

**Issue by teemukataja** [CSCfi/beacon-python#226]
#### Describe the bug
```
CREATE INDEX data_needed ON beacon_data_table
  USING btree(datasetId, chromosome, start, reference, alternate, varianttype,
              frequency, "end");
```
From https://github.com/CSCfi/beacon-python/blob/master/docs/db.rst prevents the db inserts of `insert_variants()` in `db_load.py` https://github.com/CSCfi/beacon-python/blob/master/beacon_api/utils/db_load.py#L297-L383

**Comment by blankdots** [comment]
@teemukataja what is the error that occurs ? can we have more details ?

**Comment by teemukataja** [comment]
Was unable to reproduce error, I will close this, and we can come back to it if we see it happening again
