### ISSUE TITLE
Dataset init container

### ISSUE THREAD

**Issue by blankdots** [CSCfi/beacon-python#41]
#### Proposed solution
Create a Docker container that:
- downloads e.g. 1000genome files
- uploads the files to a dataset in the database
- prints misses in variant types and other possible 

Keep the container alive after it is finished, in order to analyse data.

**Nice to have: configure endpoint from where to download data.**

#### DoD (Definition of Done)
`Dockerfile` available in `deploy` folder.

#### Testing
Peer review.

**Comment by teemukataja** [comment]
#### New dataloader script in e7ce931

New environment variables
```
FTP_URL = os.environ.get('FTP_URL', 'ftp.1000genomes.ebi.ac.uk')
FTP_DIR = os.environ.get('FTP_DIR', '/vol1/ftp/release/20130502/')
```

The script contacts given FTP (defaults to EBI's 1000 genomes repository) and downloads `*.vcf.gz` files from these and parses them into the database.
