### ISSUE TITLE
`assemblyId` from query is not used

### ISSUE THREAD

**Issue by MalinAhlberg** [CSCfi/beacon-python#57]
#### Describe the bug
The `assemblyId` from the query is not used in the DB lookup.

#### To Reproduce
Steps to reproduce the behaviour:
1. Find a query that gets a result, eg

https://beaconpy-elixirbeacon.rahtiapp.fi/query?referenceName=19&start=36585457&referenceBases=A&variantType=INS&assemblyId=GRCh38

and change the `assemblyId`, eg:

https://beaconpy-elixirbeacon.rahtiapp.fi/query?referenceName=19&start=36585457&referenceBases=A&variantType=INS&assemblyId=GRCh99

**Comment by blankdots** [comment]
Indeed a miss, will fix ... thank you for reporting.
The fix might be as simple as adding that assemblyid check to the Uber Query: https://github.com/CSCfi/beacon-python/blob/master/beacon_api/utils/data_query.py#L154
