### ISSUE TITLE
Implement GA4GH service info endpoint

### ISSUE THREAD

**Issue by blankdots** [CSCfi/beacon-python#98]
#### Description
Implement `service-info` endpoint according to https://www.ga4gh.org/how-we-work/ga4gh-product-approval/

#### DoD (Definition of Done)
`service-info` returns information regarding the Beacon service meaning what is currently in `/` endpoint. While `/` endpoint returns the specs

#### Testing
Unit tests added.

**Comment by teemukataja** [comment]
`/` endpoint to return service info as specified by Beacon API Specification
`/service-info` endpoint to return service info as specified by GA4GH Discovery Work Stream https://github.com/ga4gh-discovery/service-info
